version: '3.8'
services:
  
  wordpress:
    image: dev-wordpress
    container_name: dev-wordpress
    build:
      context: .
      dockerfile: Dockerfile-wordpress
      args:
        HOST_USER: ${VAZGEN:-www-data}
    ports:
      - "9000:80"
    volumes:
      - ./configs/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wp-content:/var/www/html/wp-content
    restart: on-failure:10
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure:10
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9500:8080"

  elasticsearch:
    image: dev-elasticsearch
    container_name: dev-elasticsearch
    build:
      context: .
      dockerfile: Dockerfile-elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      mem_limit: 2048M
      mem_reservation: 2048M
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - './configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      - 'elasticsearch_data:/usr/share/elasticsearch/data'

volumes:
  db_data:
  elasticsearch_data:
