version: '2.2'
services:
  memcached:
    image: 'memcached:latest'
  nginx:
    image: 'nginx:latest'
    expose:
      - '80'
      - '443'
    volumes:
      - './wordpress:/var/www/html:cached'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached'
    depends_on:
      - phpfpm
    networks:
      - default
      - wplocaldocker
    environment:
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
      VIRTUAL_HOST: 'digitalregulation.lcl,*.digitalregulation.lcl'
  phpfpm:
    image: wp-php-fpm-dev-7.3-ubuntu
    environment:
      ENABLE_XDEBUG: 'false'
    volumes:
      - './wordpress:/var/www/html:cached'
      - './config/php-fpm/docker-php-ext-xdebug.ini:/etc/php.d/docker-php-ext-xdebug.ini:cached'
      - 'wplocaldockerCache:/var/www/.wp-cli/cache:cached'
      - '~/.ssh:/home/ubuntu/.ssh:cached'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:cached'
    depends_on:
      - memcached
      - elasticsearch
    networks:
      - default
      - wplocaldocker
    dns:
      - 10.0.0.2
    build:
      dockerfile: .containers/php-fpm
      context: .
      args:
        PHP_IMAGE: '10up/wp-php-fpm-dev:7.3'
        CALLING_USER: ubuntu
        CALLING_UID: 1000
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.6.16'
    expose:
      - '9200'
    volumes:
      - './config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:cached'
      - './config/elasticsearch/plugins:/usr/share/elasticsearch/plugins:cached'
      - 'elasticsearchData:/usr/share/elasticsearch/data:delegated'
    mem_limit: 1024M
    mem_reservation: 1024M
    environment:
      ES_JAVA_OPTS: '-Xms450m -Xmx450m'
networks:
  wplocaldocker:
    external:
      name: wplocaldocker
volumes:
  wplocaldockerCache:
    external:
      name: wplocaldockerCache
  elasticsearchData: {}
